docs/AboutUs.md
=> Add personal description

docs/AboutUs.md
=> Add Matthew's info into AboutUs.md

docs/AboutUs.md
=> Add about us message for Wai Hin

docs/AboutUs.md
=> Add image link for munhui

docs/_config.yml
=> Add site-wide change

docs/DeveloperGuide.md
=> Add user stories and glossary

docs/DeveloperGuide.md
=> Edit product scope for DG

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/ClassId.java, src/main/java/seedu/address/model/person/Fees.java, src/main/java/seedu/address/model/person/MonthsPaid.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> Add fees, classId, monthsPaid fields

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Add fuzzy search through regex
fixes #50
=> Change find command to follow format

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/ClassIdContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
=> Add find by classid

docs/DeveloperGuide.md
fixed the extension numberings
=> Update extensions numbering

src/main/java/seedu/address/logic/commands/MarkpaidCommand.java
=> Edit comments for markpaid

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java
=> Fix code to conform to original implementation

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/main/java/seedu/address/model/person/MonthPaid.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/MarkPaidCommandTest.java
Markpaid now concatenates Strings. UI also displays months in a sorted order.
=> markPaid: concatenate strings instead of override

src/main/java/seedu/address/logic/commands/MarkPaidCommand.java, src/main/java/seedu/address/model/person/MonthPaid.java, src/main/java/seedu/address/storage/JsonAdaptedMonthPaid.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/parser/MarkPaidCommandParserTest.java, src/test/java/seedu/address/model/person/MonthPaidTest.java, src/test/java/seedu/address/storage/JsonAdaptedMonthPaidTest.java
=> Refactor MonthPaid; Add validation for invalid dates for MonthPaid

src/main/resources/view/PersonListCard.fxml
=> Add label fields to UI

src/main/java/seedu/address/ui/BarChartWindow.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PieChartWindow.java, src/main/resources/view/BarChart.css, src/main/resources/view/EdututuTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml, src/main/resources/view/PiChartWindow.fxml, src/main/resources/view/PieChart.css
=> Update UI to suit EduTuTu

build.gradle, src/main/java/seedu/address/ui/BarChartWindow.java
=> Fix warnings in bar chart

.gitignore, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/CommandStack.java, src/main/java/seedu/address/commons/core/Config.java, src/main/java/seedu/address/commons/util/CollectionUtil.java, src/main/java/seedu/address/commons/util/JsonUtil.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/CommandHistory.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyCommandHistory.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/CommandHistoryStorage.java, src/main/java/seedu/address/storage/JsonCommandHistoryStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/commons/core/ConfigTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/BarChartCommandTest.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/commands/MarkPaidCommandTest.java, src/test/java/seedu/address/logic/commands/PieChartCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java
=> Write executed commands to commandhistory.json

src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/BarChartWindow.fxml, src/main/resources/view/EdututuTheme.css, src/main/resources/view/PersonListCard.fxml, src/main/resources/view/PiChartWindow.fxml
=> Fix resize behaviour of windows

src/main/java/seedu/address/model/person/MonthPaid.java
=> Add valid dates

src/main/java/seedu/address/logic/commands/InfoCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/InfoCommandParser.java
=> Add info command skeleton

docs/diagrams/StorageClassDiagram.puml
=> Update storage uml diagram

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
=> Fix add command to display fees and classid

src/main/resources/view/EdututuTheme.css
=> Fix word color bug

src/main/java/seedu/address/commons/core/CommandGetterResult.java, src/main/java/seedu/address/commons/core/CommandStack.java, src/test/java/seedu/address/commons/core/CommandStackTest.java
Fixes #147
Solves part of #125
=> Refactor command stack; add test cases

src/main/java/seedu/address/ui/DetailedPersonCardWindow.java, src/main/resources/view/DetailedPersonCard.css, src/main/resources/view/DetailedPersonCardWindow.fxml
=> Add window sizing

src/test/java/seedu/address/logic/commands/InfoCommandTest.java, src/test/java/seedu/address/logic/parser/InfoCommandParserTest.java
=> Add tests for info command

src/main/java/seedu/address/commons/util/CollectionUtil.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/HistoricalAddressBook.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/HistoricalAddressBookTest.java
Fixes #185 
Fixes #186 
Fixes #187 
Fixes #158
* Refactor HistoricalAddressBook to use Composition instead of Inheritance
=> Refactor HistoricalAddressBook

src/main/java/seedu/address/model/person/Name.java, src/test/java/seedu/address/model/person/PersonTest.java
Fixes #201 
Fixes #203 
Improves name handling by detecting duplicates with multiple spaces
E.g. Ben Tan is now equal to Ben    Tan
Fixes #205
=> Branch fix add bug

docs/DeveloperGuide.md, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandType.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
=> Fix find command bug: Find command allows empty search after prefix

src/main/java/seedu/address/logic/commands/BarChartCommand.java
=> Implement bar chart display to be sorted in a chronological order

src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.css, src/main/resources/view/ResultDisplay.fxml
Fixes #219 
Fixes #218
Fixes #215 
Improves add functionality to accept . - and '
=> Update UI of help window; update regex of add command

src/main/java/seedu/address/model/person/ClassId.java
`Testing input` and `Matches` should not be printed.
=> Remove print statements in classId

src/main/java/seedu/address/ui/BarChartWindow.java, src/main/java/seedu/address/ui/DetailedPersonCardWindow.java, src/main/java/seedu/address/ui/PieChartWindow.java, src/main/resources/view/DetailedPersonCard.css, src/main/resources/view/DetailedPersonCardWindow.fxml, src/main/resources/view/PieChart.css
=> Fix info window

src/main/java/seedu/address/model/HistoricalAddressBook.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/model/HistoricalAddressBookTest.java
=> Limit address book history by 200

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/PersonPredicateBuilder.java, src/main/java/seedu/address/ui/DetailedPersonCardWindow.java, src/main/java/seedu/address/ui/PersonCard.java
Fixes #265
* Write custom toString() of tags and monthsPaid -> find command will search on that toString()
* Update PersonCard and info command window to display the result of the toString()
=> Make find behave more correctly

src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Refactor tests to reduce code duplication
=> Refactor tests

src/main/java/seedu/address/model/person/Fees.java
Fixes #365
This bug is allowed to be fixed as fees will throw a stacktrace error, causing the app to misbehave. The intended behaviour was to allow empty fees to be added
=> Add bug fix for fees

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/model/person/MonthPaid.java
=> Fix grammar for output message
